name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  Configuration: Release
  DOTNET_VERSION: '8.0.x'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: ⚙ dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🙏 build
        run: dotnet build --output ./output
      
      - name: 🚀 deploy
        uses: Azure/functions-action@v1
        with:
          app-name: 'shields'
          slot-name: 'Production'
          package: './output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F2539E91DB0A4D2ABCE9245FFDF97FBC }}